#!/usr/bin/env bash
# Renders deploy/overlays/aws-prod/ingress-acm-patch.yaml from:
#   1) ACM_CERTIFICATE_ARN env var, or
#   2) terraform output acm_certificate_arn (foundation; set acm_certificate_domain in tfvars), or
#   3) --from-aws REGION DOMAIN  (aws + jq; DOMAIN must match ACM "Domain name" exactly)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PATCH_REL="deploy/overlays/aws-prod/ingress-acm-patch.yaml"
PATCH="$ROOT/$PATCH_REL"
FOUNDATION="$ROOT/infra/aws/foundation"

usage() {
  echo "Usage:"
  echo "  ACM_CERTIFICATE_ARN=arn:aws:acm:region:account:certificate/uuid $0"
  echo "  $0   # uses terraform output in infra/aws/foundation if acm_certificate_domain is set"
  echo "  $0 --from-aws us-east-1 '*.k8s.example.dev'"
  exit "$1"
}

arn_from_terraform() {
  local json
  if ! json="$(cd "$FOUNDATION" && terraform output -json 2>/dev/null)"; then
    echo ""
    return 0
  fi
  echo "$json" | jq -r '.acm_certificate_arn.value // empty'
}

arn_from_aws() {
  local region="$1" domain="$2"
  aws acm list-certificates \
    --region "$region" \
    --certificate-statuses ISSUED \
    --output json |
    jq -r --arg d "$domain" '.CertificateSummaryList[] | select(.DomainName == $d) | .CertificateArn' |
    head -n1
}

FROM_AWS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --from-aws)
      [[ $# -ge 3 ]] || { echo "usage: $0 --from-aws REGION DOMAIN" >&2; exit 1; }
      FROM_AWS=("$2" "$3")
      shift 3
      ;;
    -h|--help) usage 0 ;;
    *)
      echo "unknown option: $1" >&2
      usage 1
      ;;
  esac
done

ARN="${ACM_CERTIFICATE_ARN:-}"

if [[ -z "$ARN" && ${#FROM_AWS[@]} -eq 2 ]]; then
  ARN="$(arn_from_aws "${FROM_AWS[0]}" "${FROM_AWS[1]}")"
  if [[ -z "$ARN" ]]; then
    echo "No ISSUED certificate with DomainName=${FROM_AWS[1]} in ${FROM_AWS[0]}." >&2
    exit 1
  fi
fi

if [[ -z "$ARN" ]]; then
  ARN="$(arn_from_terraform)"
fi

if [[ -z "$ARN" || "$ARN" == "null" ]]; then
  echo "Could not resolve ACM ARN. Options:" >&2
  echo "  export ACM_CERTIFICATE_ARN=arn:aws:acm:..." >&2
  echo "  set acm_certificate_domain in foundation, terraform apply, then re-run" >&2
  echo "  $0 --from-aws us-east-1 '*.k8s.example.dev'" >&2
  exit 1
fi

cat >"$PATCH" <<EOF
# Generated by scripts/render-ingress-acm-patch.sh — see docs/aws-domain-tls.md
# Argo Application deploy/gitops/apps/api.yaml syncs deploy/overlays/aws-prod when on main.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: ${ARN}
EOF

echo "Wrote $PATCH_REL"
