apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: portfolio-db
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: app
      owner: app
